port: 3000
lsi: false
permalink: /:title
markdown: kramdown

# Since GH pages override this to "true", we test this value to see if we are running locally
safe: false
include: [".well-known"]
gems:
  - jekyll-redirect-from
  - rdiscount
url: "https://nicholasarossi.github.io" # the base hostname & protocol for your site
baseurl: "/nicholasarossi"
